#MEMBERSHIP OPERATORS
'''in {RETURN TRUE IF A SEQUENCE WITH THE SPECIFIED VALUE IS PRESENT IN THE OBJECT}
not in {RETURN TRUE IF A SEQUENCE WITH THE SPECIFIED VALUE IS NOT PRESENT IN THE OBJECT}'''

# EXAMPLE
fruit=["apple","banana","mango"]
print("if banana is present in fruits:","banana"in fruit)
print("if mango is present in the fruits:","mango" in fruit)
print("if apple is present in the fruits:","apple" in fruit)
print("if guava is present in the fruits:", "guava" in fruit)
print("if guava is not present in the fruits:","guava" not in fruit)