'''DATA TYPE IN PYTHON 
1. NUMERIC    2. DICTIONARY   3. BOOLEAN    4. SET   5. SEQUENCE
I.INTEGER  II.FLOAT  III.COMPLEX                      I.STRING II.TUPLE  III.LIST '''

'''INT [1,2,-1,-8] FLOAT[2.0,3.6] COMPLEX[2+4j,1+3i] STRING["LISA","PIA"] TUPLE(1,45,34) LIST[1,4,3] DICTIONARY{"NAME": PIA,"AGE":23}  BOOLEAN True False
SET {UNORDERED COLLECTION OF UNIQUE ITEMS} {"APPLE","MANGO"}     NONE: NO VALUE'''


'''ASCII AND UNICODE VALUE (american standard code for information interchange)
A-Z (65-90)
a-z (97-122)
0-9 (48-57)
space (32)'''

'''ord() function use to find the code of any character (must use'')'''
x='A'
print(ord(x))
y='3'
print(ord(y))


'''chr() function is used to find the ascii value of any character {don't use any ''} '''
w=65
print(chr(w))
z=89
print(chr(z))