# TAKING INPUT USING input() function
x= input("enter your name:")
print(x)

# we can use this into one line 
y=print(input("enter your age:"))

# we can add the datatype with input we choose that what kind of data we want from user like integer or string
#by default in python there is str datatype

z=int(input("enter your salary:"))

# in input() function it doesn't require any print statement bcz it directly show to the user 

#TYPECASTING: CONVERTING ONE DATATYPE TO ANOTHER DATATYPE