# CONDITIONAL AND LOOPS
# CONTROL STATEMENTS (THEY ALLOW US TO CONTROL THE FLOW OF OUR PROGRAM)
'''CONDITIONALS 
if , if-else
nested
else if ladder
ternary
switch'''
# if-else
'''if statement conditional statisfy then print if staement otherwise print else staement'''
# example
raining= input("enter choice: ")
if raining == "raining":
    print("take umbrella")
else:
    print("don't take umberlla")

