#FOR LOOP AND WHILE LOOP.
'''for i in range (start,stop,step):

first initialisation (i=1) -> start
then check the termination condition (i>10) if termination condition not meet then 
execute the task (print) and update looping (i+1). bydefault if there is no step given then it take +1 and 
if no start is given then it start from 0

if the termination condition meet then it break or stop the task and stop is executive'''
#EXAMPLE : PRINT "HELLO WORLD" 10 TIMES.
for i in range (1,11,1):
    print(i,"hello world")